# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:8.11.1

stages:
  - build
before_script:

  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_DEV_KEY")
  - ssh-add <(echo "$SSH_PRIVATE_REL_KEY")
  - ssh-add <(echo "$SSH_PRIVATE_KEY")

  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:

dev:
  stage: build
  script:
   - echo "[STEP 1] start to git pull on all servers."
   - ssh -tt -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${SSH_USER}@${DEV_HOST} -p 22 "cd ${API_DIR} && git stash && git checkout develop && git fetch && git pull" # must be Double quotes, the single quotes will return ${SERVICE_DIR} string instead of ${SERVICE_DIR} varible
   
   - echo "[STEP 2] start to npm install on all servers."
   - ssh -tt -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${SSH_USER}@${DEV_HOST} -p 22 "cd ${API_DIR} && npm install" # must be Double quotes, the single quotes will return ${SERVICE_DIR} string instead of ${SERVICE_DIR} varible
  
   - echo "[STEP 3] restart each node via pm2 on all servers."
   - ssh -tt -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${SSH_USER}@${DEV_HOST} -p 22 "cd ${API_DIR} && pm2 restart pm2.json" # must be Double quotes, the single quotes will return ${SERVICE_DIR} string instead of ${SERVICE_DIR} varible
  
   - echo "[SUCCEEDED] develop has been deployed."
  only:
    refs:
      - develop

rel:
  stage: build
  script:
   - echo "[STEP 1] start to git pull on all servers."
   - ssh -tt -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${SSH_USER}@${DEV_HOST} -p 22 "cd ${API_DIR} && git stash && git checkout develop && git fetch && git pull" # must be Double quotes, the single quotes will return ${SERVICE_DIR} string instead of ${SERVICE_DIR} varible
   
   - echo "[STEP 2] start to npm install on all servers."
   - ssh -tt -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${SSH_USER}@${DEV_HOST} -p 22 "cd ${API_DIR} && npm install" # must be Double quotes, the single quotes will return ${SERVICE_DIR} string instead of ${SERVICE_DIR} varible
  
   - echo "[STEP 3] restart each node via pm2 on all servers."
   - ssh -tt -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${SSH_USER}@${DEV_HOST} -p 22 "cd ${API_DIR} && pm2 restart pm2.json" # must be Double quotes, the single quotes will return ${SERVICE_DIR} string instead of ${SERVICE_DIR} varible
  
   - echo "[SUCCEEDED] develop has been deployed."
  only:
    refs:
      - develop

