# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8.10.0

pipelines:  
  branches:
    default:
      - step:
          script:
            - rm -Rf ~/.ssh/knon_host
    develop:
      - step:
          script:
            - ssh -tt -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null '$SSH_USER'@`$SCHEDULE_IP` -p 22 'cd ${SERVICE_DIR} && npm install'
            - ssh -tt -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${SSH_USER}@{$SERVICE_1_IP} -p 22 'cd ${SERVICE_DIR} && npm install'
            - ssh -tt -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${SSH_USER}@`${SERVICE_2_IP} -p 22 'cd ${SERVICE_DIR} && npm install'
            - echo "develop ends..."
    release:
      - step:
          script:
            - echo "release ends..."
    master:
      - step:
          script:
            - ssh -tt -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@45.33.40.237 -p 22 'cd SERVICE_DIR && npm install'
            - ssh -tt -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SSH_USER@$SERVICE_1_IP -p 22 'cd SERVICE_DIR && npm install'
            - ssh -tt -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SSH_USER@$SERVICE_2_IP -p 22 'cd SERVICE_DIR && npm install'
            - echo "master ends..."

