# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8.10.0

pipelines:  
  branches:
    default:
      - step:
          script:
            - rm -Rf ~/.ssh/knon_host
    develop:
      - step:
          script:
            - echo "[STEP 1] start to git pull on all servers."
            - ssh -tt -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${SSH_USER}@${SERVICE_DEV_IP} -p 22 "cd ${SERVICE_DIR} && git stash && git checkout master && git fetch && git pull" # must be Double quotes, the single quotes will return ${SERVICE_DIR} string instead of ${SERVICE_DIR} varible

            - echo "[STEP 2] start to npm install on all servers."
            - ssh -tt -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${SSH_USER}@${SERVICE_DEV_IP} -p 22 "cd ${SERVICE_DIR} && npm install" # must be Double quotes, the single quotes will return ${SERVICE_DIR} string instead of ${SERVICE_DIR} varible
            
            - echo "[STEP 3] restart each node via pm2 on all servers."
            - ssh -tt -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${SSH_USER}@${SERVICE_DEV_IP} -p 22 "cd ${SERVICE_DIR} && pm2 restart pm2.json" # must be Double quotes, the single quotes will return ${SERVICE_DIR} string instead of ${SERVICE_DIR} varible
            
            - echo "[SUCCEEDED] develop has been deployed."
    release:
      - step:
          script:
            - echo "[SUCCEEDED] release has been deployed."
    master:
      - step:
          script:
            - echo "[STEP 1] start to git pull on all servers."
            - ssh -tt -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${SSH_USER}@${SCHEDULE_IP} -p 22 "cd ${SERVICE_DIR} && git stash && git checkout master && git fetch && git pull" # must be Double quotes, the single quotes will return ${SERVICE_DIR} string instead of ${SERVICE_DIR} varible
            - ssh -tt -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${SSH_USER}@${SERVICE_1_IP} -p 22 "cd ${SERVICE_DIR} && git stash && git checkout master && git fetch && git pull"
            - ssh -tt -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${SSH_USER}@${SERVICE_2_IP} -p 22 "cd ${SERVICE_DIR} && git stash && git checkout master && git fetch && git pull"

            - echo "[STEP 2] start to npm install on all servers."
            - ssh -tt -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${SSH_USER}@${SCHEDULE_IP} -p 22 "cd ${SERVICE_DIR} && npm install" # must be Double quotes, the single quotes will return ${SERVICE_DIR} string instead of ${SERVICE_DIR} varible
            - ssh -tt -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${SSH_USER}@${SERVICE_1_IP} -p 22 "cd ${SERVICE_DIR} && npm install"
            - ssh -tt -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${SSH_USER}@${SERVICE_2_IP} -p 22 "cd ${SERVICE_DIR} && npm install"
            
            - echo "[STEP 3] restart each node via pm2 on all servers."
            - ssh -tt -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${SSH_USER}@${SCHEDULE_IP} -p 22 "cd ${SERVICE_DIR} && pm2 start pm2.json --only schedule.chatshier" # must be Double quotes, the single quotes will return ${SERVICE_DIR} string instead of ${SERVICE_DIR} varible
            - ssh -tt -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${SSH_USER}@${SERVICE_1_IP} -p 22 "cd ${SERVICE_DIR} && pm2 start pm2.json --only service.chatshier"
            - ssh -tt -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${SSH_USER}@${SERVICE_2_IP} -p 22 "cd ${SERVICE_DIR} && pm2 start pm2.json --only service.chatshier"
            
            - echo "[SUCCEEDED] master has been deployed."

